[build]
target = "riscv32imc-unknown-none-elf"
rustflags = []

[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --port /dev/tty.usbmodem101 --monitor --ignore-app-descriptor"

[alias]
flash = "run --release"
