[build]
target = "riscv32imc-unknown-none-elf"
rustflags = []

[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --port COM5 --monitor --ignore-app-descriptor"

# [alias]
# flash = "run --release"
